name: wang-2021
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - scipy
  - pytest
  - matplotlib
  - ipython
  - jupyterlab
  - myst-nb
  - jupytext
  - nodejs
  - pip
  - pip:
    - pyscf
    - geometric
